version: "3.8"

services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/mnt/data
      - ./database:/app/database
      - ./delta_tables:/app/delta_tables
    # environment:
    # - DATABASE_URL=sqlite:///app/database/requests.db
    networks:
      - mynetwork

  spark:
    image: jupyter/pyspark-notebook
    ports:
      - "8888:8888"
    volumes:
      - delta_storage:/app/delta_tables
      - ./notebooks:/home/jovyan/notebooks # Mount local notebooks to the container jovyan is the root user?
      - ./data:/mnt/data

    networks:
      - mynetwork

  streamlit:
    build:
      context: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - fastapi
    volumes:
      - ./frontend:/app/frontend
    networks:
      - mynetwork

volumes:
  delta_storage: # Persistent volume for Delta Lake storage

networks:
  mynetwork:
    driver: bridge
